name: Publish labs
on:
  push:
    branches:
    # - master
      - lm/ocw-update
    # paths:
    #   - '*/*/README.md'
jobs:
  publish_labs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Update labs
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PP_OCW_PRIVATE_KEY }}
          SSH_PASSPHRASE: ${{ secrets.PP_OCW_PASSPHRASE }}
        run: |
          eval "$(ssh-agent -s)"

          echo "$SSH_PRIVATE_KEY" > /tmp/ssh_key
          chmod 600 /tmp/ssh_key

          export SSH_ASKPASS_REQUIRE=force
          export SSH_ASKPASS=$(mktemp)
          echo "#!/bin/sh" > "$SSH_ASKPASS"
          echo "echo \"\$SSH_PASSPHRASE\"" >> "$SSH_ASKPASS"
          chmod +x "$SSH_ASKPASS"

          ssh-add /tmp/ssh_key

          rm /tmp/ssh_key "$SSH_ASKPASS"

          ./scripts/update-ocw.sh
