name: Running solutions
on: [push]

jobs:
    run-sols:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Install Racket
              uses: Bogdanp/setup-racket@v1.5
              with:
                architecture: 'x64'
                distribution: 'full'
                variant: 'CS'
                version: '8.15'
            - name: Run Racket solutions
              run: |
                racket ./racket/intro/solutii/*.rkt
                racket ./racket/recursivitate/solutii/*.rkt
                racket ./racket/functionale/solutii/*.rkt
                racket ./racket/legare/solutii/*.rkt
                racket ./racket/intarzierea-evaluarii/solutii/*.rkt
