name: Creating zip archives and publish them

on:
  push:
    branches:
      - master
    paths:
      - '*/*/*/*.rkt'
      - '*/*/*/*.hs'
      - '*/*/*/*.pl'

jobs:
  zip-and-upload:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Zip the file
        run: |
          zip -r racket-intro-skel.zip ./racket/intro/schelet/palindromes.rkt
          zip -r racket-intro-sol.zip ./racket/intro/solutii/palindromes.rkt

      - name: Upload archives
        uses: actions/upload-artifact@v4
        with:
          name: archives
          path: |
            racket-intro-skel.zip
            racket-intro-sol.zip
