name: Creating zip archives and publish them

on:
  push:
    branches:
      - master
    paths:
      - '*/*/*/*.rkt'
      - '*/*/*/*.hs'
      - '*/*/*/*.pl'

jobs:
  zip-and-upload:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Zip code
        uses: vimtor/action-zip@v1.2
        with:
            files: ./racket/intro/schelet/palindromes.rkt
            dest: racket-intro-skel.zip

      - name: Upload archives
        uses: actions/upload-artifact@v4
        with:
          name: racket-intro-skel
          path: racket-intro-skel.zip
          target: racket-intro-skel
          overwrite: true