name: Creating zip archives and publish them

on:
  push:
    branches:
      - master
    paths:
      - '*/*/*/*.rkt'
      - '*/*/*/*.hs'
      - '*/*/*/*.pl'

jobs:
  zip-and-upload:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Execute archives script
        run: cd scripts && ./create-archives.sh