name: Creating zip archives and publish them

on:
  push:
    branches:
      - master
    paths:
      - '*/*/*/*.rkt'
      - '*/*/*/*.hs'
      - '*/*/*/*.pl'
    tags:
      - '*'

jobs:
  zip-and-upload:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Archive - Racket - lab 1 - skel
        uses: vimtor/action-zip@v1.2
        with:
            files: ./racket/intro/schelet/palindromes.rkt
            dest: racket-intro-skel.zip

      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
            draft: false
            prerelease: false
            release_name: ${{ steps.version.outputs.version }}
            tag_name: Release ${{ github.ref }}
        env:
            GITHUB_TOKEN: ${{ github.token }}
      - name: Upload archive - Racket - lab 1 - skel
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./racket-intro-skel.zip
          asset_name: racket-intro-skel.zip
          asset_content_type: application/zip